kind: Service
apiVersion: v1
metadata:
  name: example-country-service
spec:
  selector:
    app: example-country-service
  ports:
    - protocol: TCP
      port: 50700
      nodePort: 30100 #this is the external port
  type: NodePort