apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
spec:
  selector:
    matchLabels:
      app: postgres
  replicas: 1
  strategy:
    type: Recreate #RollingUpdate
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
        - name: postgres
          image: postgres:12.4
          imagePullPolicy: IfNotPresent #Always
          ports:
            - containerPort: 5432
          args:
            - postgres
            - -c
            - shared_buffers=128MB
            - -c
            - max_connections=30
            - -c
            - shared_preload_libraries=pg_stat_statements
          envFrom:
            - secretRef:
                name: example-postgres-secret
          volumeMounts:
            - mountPath: /docker-entrypoint-initdb.d/
              name: initdb
            - mountPath: /var/lib/postgresql/data
              name: pgdata

      volumes:
        - name: initdb
          configMap:
            name: example-postgres-initdb
        - name: pgdata
          persistentVolumeClaim:
            claimName: example-postgres-pvc