apiVersion: v1
kind: ConfigMap
metadata:
  name: country-service-application-configmap
data:
  TZ: Europe/Berlin
  spring.config.location: /usr/share/config/application.yml
  logging.config: /usr/share/config/logback-rollingfile-spring.xml
  spring.datasource.url: "jdbc:postgresql://country-service-postgres:5432/countrydb"
  management.database.monitoring.enabled: "true"

  #externals
  adapter.calleeservice.url: "http://callee-service-application:50900"

  #stageing
  server.tomcat.threads.max: "20"

  spring.datasource.hikari.maximum-pool-size: "10"
  spring.datasource.hikari.connection-timeout: "10000"

  resilience4j.circuitbreaker.configs.default.slowCallDurationThreshold: "10000"

---

apiVersion: v1
kind: Secret
metadata:
  name: country-service-application-secret
data:
  adapter.calleeservice.user: ZXhhbXBsZXVzZXI=
  #exampleuser
  adapter.calleeservice.password: RU5DKExnQ1Q0a3JXNU5EclFrZkdQUEVZdzdYT3Z6dWZ2SUFOV0ZxM3ZIb3crU3BoZDZBQ3RhdmFoVzhhTDI4TkRubVpleDUrUG56MTRORWVEdVIrWkk5MHNRPT0p
  #ENC(LgCT ...) => we should replace jasypt we kubernetes aes256 secrets here


