apiVersion: v1
kind: ConfigMap
metadata:
  name: ${_Values_app_name}-configmap
data:
  TZ: Europe/Berlin
  spring.config.location: /usr/share/config/application.yml
  logging.config: /usr/share/config/logback-rollingfile-spring.xml

  server.port: "${_Values_service_port}"

  #monitoring
  server.forward-headers-strategy: FRAMEWORK
  management.database.monitoring.enabled: "true"
  management.endpoints.web.exposure.include: "info,health,heapdump,circuitbreakers,prometheus"

  #stageing
  server.tomcat.threads.max: "20"

  spring.datasource.hikari.maximum-pool-size: "10"
  spring.datasource.hikari.connection-timeout: "10000"

  resilience4j.circuitbreaker.configs.default.slowCallDurationThreshold: "10000"

  database.provisioning.goals: -migrate

---

#Secrets to external resources

apiVersion: v1
kind: Secret
metadata:
  name: ${_Values_app_name}-secret
stringData:
  spring.datasource.url: "jdbc:postgresql://country-service-postgres:5432/countrydb"
  adapter.calleeservice.url: "http://callee-service-application:50100"
data:
  spring.datasource.username: ZXhhbXBsZS1zZXJ2aWNl
  spring.datasource.password: Y3JOYjJaNm12QnlTUkt3dQ==

  adapter.calleeservice.user: ZXhhbXBsZXVzZXI=
  adapter.calleeservice.password: RU5DKExnQ1Q0a3JXNU5EclFrZkdQUEVZdzdYT3Z6dWZ2SUFOV0ZxM3ZIb3crU3BoZDZBQ3RhdmFoVzhhTDI4TkRubVpleDUrUG56MTRORWVEdVIrWkk5MHNRPT0p

