apiVersion: v1
kind: ConfigMap
metadata:
  name: country-service-application-configmap
data:
  TZ: Europe/Berlin
  spring.config.location: /usr/share/config/application.yml
  logging.config: /usr/share/config/logback-rollingfile-spring.xml
  spring.datasource.url: "jdbc:postgresql://country-service-postgres:5432/countrydb"
  management.database.monitoring.enabled: "true"

  #stageing
  server.tomcat.threads.max: "20"

  spring.datasource.hikari.maximum-pool-size: "10"
  spring.datasource.hikari.connection-timeout: "10000"

  resilience4j.circuitbreaker.configs.default.slowCallDurationThreshold: "10000"
  adapter.calleeservice.url: "http://callee-service-application:50900"

---

apiVersion: v1
kind: Secret
metadata:
  name: country-service-application-secret
data:
  spring.datasource.username: ZXhhbXBsZS1zZXJ2aWNl
  spring.datasource.password: Y3JOYjJaNm12QnlTUkt3dQ==


