apiVersion: v1
kind: Secret
metadata:
  name: ${_Values_app_name}-secret
stringData:
  spring.datasource.url: "jdbc:postgresql://${_Values_root_name}-service-postgres:5432/${_Values_root_name}"
  adapter.calleeservice.url: "http://callee-service-application:50100"
data:
  spring.datasource.username: ZXhhbXBsZS1zZXJ2aWNl
  spring.datasource.password: Y3JOYjJaNm12QnlTUkt3dQ==

  adapter.calleeservice.user: ZXhhbXBsZXVzZXI=
  adapter.calleeservice.password: RU5DKExnQ1Q0a3JXNU5EclFrZkdQUEVZdzdYT3Z6dWZ2SUFOV0ZxM3ZIb3crU3BoZDZBQ3RhdmFoVzhhTDI4TkRubVpleDUrUG56MTRORWVEdVIrWkk5MHNRPT0p
