kind: Service
apiVersion: v1
metadata:
  name: country-service-application
spec:
  selector:
    app: country-service-application
  ports:
    - protocol: TCP
      port: 50700
      nodePort: 30940 #this is the external port
  type: NodePort