#!/bin/bash
source .values

export COMMAND=$1
export DEPLOYMENT_NAME=welcome-board-application

function up() {
    [ -d "./config/" ] && kubectl create configmap ${DEPLOYMENT_NAME}-config-files --from-file=./config/ -n ${NAMESPACE}
    [ -d "./config/data/" ] && kubectl create configmap ${DEPLOYMENT_NAME}-data-files --from-file=./config/data/ -n ${NAMESPACE}
    [ -d "./templates/pvc/" ] && kubectl apply -f ./templates/pvc/ -n ${NAMESPACE}
    kubectl apply -f ./templates/ -n ${NAMESPACE}
}

function down() {
    [ -d "./config/" ] && kubectl delete --ignore-not-found configmap ${DEPLOYMENT_NAME}-config-files -n ${NAMESPACE}
    [ -d "./config/data/" ] && kubectl delete --ignore-not-found configmap ${DEPLOYMENT_NAME}-data-files -n ${NAMESPACE}
    kubectl delete --ignore-not-found -f ./templates -n ${NAMESPACE}
}

if [ "${COMMAND}" = "init" ]
then
    up
#elif [ "${COMMAND}" = "down" ]
#then
#    down
elif [ "${COMMAND}" = "prune" ]
then
    down
    [ -d "./templates/pvc/" ] && kubectl delete --ignore-not-found -f ./templates/pvc/ -n ${NAMESPACE}
else
    echo Doing nothing !
fi
