#!/bin/bash
source .env

export COMMAND=$1

function func_create_application {
    kubectl apply -f ./deployment/application/
}

function func_delete_application {
    kubectl delete --ignore-not-found -f ./deployment/application/
}


if [ "${COMMAND}" = "up" ]
then
    kubectl run echoserver --image=gcr.io/google_containers/echoserver:1.4 --port=8080
    kubectl expose deployment echoserver --type=NodePort
    minikube service echoserver

    func_create_application
elif [ "${COMMAND}" = "down" ]
then
    kubectl delete namespace cheese
elif [ "${COMMAND}" = "prune" ]
then
    func_prune
else
    echo Doing nothing !
fi
