version: "3"


services:
  exampleservice:
    # replace username/repo:tag with your name and image details
    image: goafabric/spring-boot-exampleservice:1.0.0-SNAPSHOT
    container_name: exampleservice
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: "1"
          memory: 128M
      restart_policy:
        condition: on-failure
    ports:
      - "8080:8080"
    environment:
      - spring.datasource.url=jdbc:postgresql://host.docker.internal:5432/countrydb

    networks:
      - example_net

  postgres:
    image: postgres:9.5-alpine
    container_name: postgres
    expose:
    - "5432"
    ports:
    - "5432:5432"
    environment:
    - POSTGRES_USER=postgres
    - POSTGRES_PASSWORD=postgres
    - POSTGRES_DB=countrydb
    networks:
    - example_net

networks:
  example_net: