version: "3"
services:
  web:
    # replace username/repo:tag with your name and image details
    image: goafabric/spring-boot-exampleservice:stable
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: "2"
          memory: 100M
      restart_policy:
        condition: on-failure
    ports:
      - "8080:8080"
    networks:
      - webnet
networks:
  webnet: