apiVersion: v1
kind: Service
metadata:
  name: elasticsearch
spec:
  ports:
    - name: "9200"
      port: 9200
      targetPort: 9200
  selector:
    app: elasticsearch
status:
  loadBalancer: {}

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: elasticsearch
spec:
  selector:
    matchLabels:
      app: elasticsearch
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: elasticsearch
    spec:
      containers:
      - env:
        - name: ES_JAVA_OPTS
          value: -Xms1g -Xmx1g
        - name: TZ
          value: Europe/Berlin
        - name: cluster.name
          value: elasticsearch
        - name: discovery.type
          value: single-node
        - name: http.enabled
          value: "true"
        - name: transport.tcp.port
          value: "9300"
        - name: xpack.graph.enabled
          value: "false"
        - name: xpack.ml.enabled
          value: "false"
        - name: xpack.monitoring.enabled
          value: "false"
        - name: xpack.security.enabled
          value: "false"
        - name: xpack.watcher.enabled
          value: "false"
        image: docker.elastic.co/elasticsearch/elasticsearch:5.4.3
        livenessProbe:
          httpGet:
            path: /
            port: 9200
          initialDelaySeconds: 30
          periodSeconds: 5
          timeoutSeconds: 10
          failureThreshold: 3
        name: elasticsearch
        ports:
        - containerPort: 9200
        resources: {}
        volumeMounts:
        - mountPath: /usr/share/elasticsearch/data
          name: esdata
#        - mountPath: /usr/share/elasticsearch/config
#          name: esconfig
        - mountPath: /usr/share/elasticsearch/logs
          name: eslogs
        - mountPath: /usr/share/elasticsearch/config/jvm.options
          subPath: jvm.options
          name: elasticsearch-config-files-volume

      restartPolicy: Always
      volumes:
      - name: esdata
        persistentVolumeClaim:
          claimName: esdata
#      - name: esconfig
#        emptyDir: {}
      - name: eslogs
        emptyDir: {}
      - name: elasticsearch-config-files-volume
        configMap:
          name: elasticsearch-config-files

status: {}

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  creationTimestamp: null
  labels:
    app: esdata
  name: esdata
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1000Mi
status: {}