apiVersion: v1
kind: Service
metadata:
  name: elasticsearch
spec:
  selector:
    app: elasticsearch
  ports:
    - protocol: TCP
      port: 9200
  type: ClusterIP


---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: elasticsearch
spec:
  selector:
    matchLabels:
      app: elasticsearch
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: elasticsearch
    spec:
      containers:
      - name: elasticsearch
        image: docker.elastic.co/elasticsearch/elasticsearch:5.4.3
        livenessProbe:
          httpGet:
            path: /
            port: 9200
          initialDelaySeconds: 30
          periodSeconds: 5
          timeoutSeconds: 10
          failureThreshold: 3
        envFrom:
          - configMapRef:
              name: elasticsearch-config
        ports:
        - containerPort: 9200
        resources: {}
        volumeMounts:
        - mountPath: /usr/share/elasticsearch/data
          name: esdata
#        - mountPath: /usr/share/elasticsearch/config
#          name: esconfig
        - mountPath: /usr/share/elasticsearch/logs
          name: eslogs
        - mountPath: /usr/share/elasticsearch/config/jvm.options
          subPath: jvm.options
          name: elasticsearch-config-files-volume

      restartPolicy: Always
      volumes:
      - name: esdata
        persistentVolumeClaim:
          claimName: esdata
#      - name: esconfig
#        emptyDir: {}
      - name: eslogs
        emptyDir: {}
      - name: elasticsearch-config-files-volume
        configMap:
          name: elasticsearch-config-files

status: {}

---

apiVersion: v1
kind: ConfigMap
metadata:
  name: elasticsearch-config
data:
  ES_JAVA_OPTS: -Xms1g -Xmx1g
  TZ: Europe/Berlin
  cluster.name: elasticsearch
  discovery.type: single-node
  http.enabled: "true"
  transport.tcp.port: "9300"
  xpack.graph.enabled: "false"
  xpack.ml.enabled: "false"
  xpack.security.enabled: "false"
  xpack.watcher.enabled: "false"

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  creationTimestamp: null
  labels:
    app: esdata
  name: esdata
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1000Mi
status: {}