kind: Service
apiVersion: v1
metadata:
  name: pgadmin-application
spec:
  selector:
    app: pgadmin-application
  type: NodePort
  ports:
    - protocol: TCP
      port: 5050
      nodePort: 32500 #this is the external port
