#!/bin/bash

export COMMAND=$1

if [ "${COMMAND}" = "prov" ]
then
    kubectl create namespace example
elif [ "${COMMAND}" = "prune" ]
then
    kubectl delete namespace example
else
    echo Doing nothing !
fi