apiVersion: v1
kind: ConfigMap
metadata:
  name: example-application-configmap
data:
  TZ: Europe/Berlin
  tomcat.max-threads: "20"
  spring.config.location: /usr/share/config/application.yml
  logging.config: /usr/share/config/logback-rollingfile-spring.xml

---

apiVersion: v1
kind: Secret
metadata:
  name: example-application-secret
data:


