kind: Service
apiVersion: v1
metadata:
  name: callee-service-application
spec:
  selector:
    app: callee-service-application
  ports:
    - protocol: TCP
      port: 50900
      nodePort: 30900 #this is the external port
  type: NodePort

---

apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: callee-service-ingress
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/rewrite-target: /$2
#    nginx.ingress.kubernetes.io/proxy-read-timeout: "3600"
spec:
  tls:
    - hosts:
        - goafabric.org
      secretName: tls-secret
  rules:
    - host: goafabric.org
      http:
        paths:
          - path: /callee(/|$)(.*)
            backend:
              serviceName: callee-service-application
              servicePort: 50900