apiVersion: v1
kind: Secret
metadata:
  name: ${_Values_app_name}-config-external
stringData:
  #datasource
  spring.datasource.url: "jdbc:postgresql://country-service-postgres:5432/country"
  spring.datasource.hikari.maximum-pool-size: "10"
  spring.datasource.hikari.connection-timeout: "10000"

  database.provisioning.goals: -migrate -import-demo-data -terminate # migrate is also needed because we misuse the service as batch here

data:
  spring.datasource.username: ZXhhbXBsZS1zZXJ2aWNl
  spring.datasource.password: Y3JOYjJaNm12QnlTUkt3dQ==
