apiVersion: v1
kind: ConfigMap
metadata:
  name: ${_Values_app_name}-config-files

data:
  logback-spring.xml: >-
    <?xml version="1.0" encoding="UTF-8"?>
    <configuration><include resource="org/springframework/boot/logging/logback/default.xml"/><include resource="org/springframework/boot/logging/logback/console-appender.xml" /><include resource="org/springframework/boot/logging/logback/file-appender.xml" />
    <root level="WARN"><appender-ref ref="CONSOLE" /><appender-ref ref="FILE" /></root></configuration>
