server:
  port: 50700
  tomcat.max-threads: 20

management:
    endpoint:
      health:
        show-details: always
    endpoints:
      web:
        exposure:
          include: "info,health"

info:
    status: ok

spring:
    datasource:
      url: jdbc:h2:mem:countrydb
      #url: jdbc:postgresql://localhost:5432/countrydb
      username: postgres
      password: postgres

      hikari:
        maximum-pool-size: 10

    flyway:
      locations: classpath:db/migration
#      schemas: countries

security:
  authentication:
    enabled: true
  credentials:
    user: admin
    password: "{bcrypt}$2a$10$oivPaAOLxh2bbS7kgob3seOh6WpzmoAgLWOjxtnf81Hyxn5O7ZV9W"
