server:
  port: 50700
  tomcat:
    threads:
      max: 20

## actuator section
management:
    endpoints:
      web:
        exposure:
          include: "info,health,heapdump,prometheus,circuitbreakers,circuitbreakerevents"
    endpoint:
      health:
        show-details: always
    health:
      circuitbreakers:
        enabled: true
    database:
      monitoring:
        enabled: false

## persistence section
spring:
    datasource:
      url: jdbc:h2:mem:countrydb
#      url: jdbc:postgresql://kubernetes:30710/countrydb
      username: example-service
      password: example-service

      hikari:
        maximum-pool-size: 10
        connection-timeout: 10000 #timeout in ms

    flyway:
      locations: classpath:db/migration

database:
  provisioning:
    goals: -migrate -import-demo-data
#    goals: -migrate -encryptproperty=secret -terminate
#    goals: -migrate -import-catalog-data -terminate
    demo-data-location: filesystem:src/deploy/config/application/demodata


## encryption section
security:
  authentication:
    enabled: true

# cache
cache:
  maxsize: 1000
  expiry: 15

## adapter section
adapter:
  timeout: 10000 #timeout in ms
  calleeservice:
    url: http://localhost:50900
    user: exampleuser
    #Please note this password gets encoded with the existing key inside the config database table, .i.e. changing the key results in an invalid password here
    #In this case you have to update the passphrase inside the database, put an empty password here, and start the application with -encryptproperty to encrypt the prop with the new passphrase
    password: ENC(LgCT4krW5NDrQkfGPPEYw7XOvzufvIANWFq3vHow+Sphd6ACtavahW8aL28NDnmZex5+Pnz14NEeDuR+ZI90sQ==)

resilience4j.circuitbreaker:
  configs:
    default:
      #see for more informations under: https://resilience4j.readme.io/docs/circuitbreaker
      registerHealthIndicator: true
      slowCallDurationThreshold: ${adapter.timeout} #Effectively the timeout
      slowCallRateThreshold: 100 #Percentage of calls that that need be registered a slow for the CB to transitions from close to open
      failureRateThreshold: 50 #Failure rate when the Circuit Breaker transitions from closed to open
      waitDurationInOpenState: 60s #Time the CircuitBreaker should wait before transitioning back from open to half-open.

      minimumNumberOfCalls: 10 #The minimum number of calls which are required before the CircuitBreaker can calculate the error rate.
      permittedNumberOfCallsInHalfOpenState: 10 #Number of permitted calls when the CircuitBreaker is half open.
  instances:
    calleeservice:
      baseConfig: default

#opentracing.jaeger.disabled: "false"
#opentracing.jaeger.http-sender.url: "http://jaeger-collector.istio-system.svc:14268/api/traces"
#opentracing.jaeger.service-name: "country-service"

#log levels
logging.level.root: "WARN"
logging.level.org.goafabric: "INFO"

logging.level.org.springframework: "INFO"
logging.level.org.flywaydb.core: "INFO"
logging.level.org.hibernate.SQL: "INFO"

logging.pattern.console: "%white(%d{ISO8601}) %highlight(%-5level) [%blue(%t)] %yellow(%C{1.}): %msg%n%throwable"
