server:
  port: 50700
  tomcat.max-threads: 10

#    http2:
#      enabled: true
#    ssl:
#      key-store: classpath:keystore.jks
#      key-store-password: password

management:
    endpoint:
      health:
        show-details: always
    endpoints:
      web:
        exposure:
          include: "*"

info:
    status: ok


spring:
    datasource:
      url: jdbc:h2:mem:test
      #url: jdbc:h2:mem:test;INIT=RUNSCRIPT FROM 'classpath:db/migration/V1__init.sql'
      #url: jdbc:postgresql://localhost:5432/countrydb
      username: postgres
      password: postgres

      hikari:
        maximum-pool-size: 10

    flyway:
      locations: classpath:db/migration
      baseline-on-migrate: true
      enabled: true
