server:
  port: 8080
  tomcat.max-threads: 10

#    http2:
#      enabled: true
#    ssl:
#      key-store: classpath:keystore.jks
#      key-store-password: password

management:
    endpoint:
      health:
        show-details: always
    endpoints:
      web:
        exposure:
          include: "*"

info:
    status: ok


spring:
    datasource:
      url: jdbc:h2:mem:test
      username: postgres
      password: postgres

      hikari:
        maximum-pool-size: 100
        connection-test-query: "SELECT 1"

    flyway:
#  locations: classpath:db/migration
      baseline-on-migrate: true
      enabled: true
