server:
#    http2:
#      enabled: true
#    ssl:
#      key-store: classpath:keystore.jks
#      key-store-password: password

management:
    endpoint:
      health:
        show-details: always
    endpoints:
      web:
        exposure:
          include: "*"

info:
    status: ok

#db:
#    username: sa
#    password:
#    poolsize: 100
#    url: jdbc:h2:mem:test
    #;INIT=RUNSCRIPT FROM 'classpath:schema.sql'
#    url: jdbc:h2:tcp://localhost/~/database/spring

spring:
    datasource:
      url: jdbc:h2:mem:test
      #url: jdbc:postgresql://localhost:5432/countrydb
      username: postgres
      password: postgres


      hikari:
        maximum-pool-size: 100
        connection-test-query: "SELECT 1"

    flyway:
      #url: jdbc:h2:mem:test
      #url: jdbc:postgresql://localhost:5432/countrydb

#  locations: classpath:db/migration
      baseline-on-migrate: true
      enabled: true
