#management endpoints
#management.server.context-path=/management
#endpoints.health.sensitive=false
#endpoints.trace.enabled=false
#management.endpoints.web.base-path=/manage

server:
    http2:
      enabled: true
    ssl:
      key-store: classpath:keystore.jks
      key-store-password: password

management:
    endpoints:
      web:
        exposure:
          include: "*"

info:
    status: ok

db:
    username: sa
    password:
    poolsize: 100
    url: jdbc:h2:mem:test;INIT=RUNSCRIPT FROM 'classpath:init_database.sql'



#spring:
#    datasource:
#      url: jdbc:h2:mem:test
#      username: sa
#      password:
#      hikari:
#        maximum-pool-size: 100
#        connection-test-query: "SELECT 1"
