server:
  port: 50700
  tomcat.max-threads: 20

management:
    endpoints:
      web:
        exposure:
          include: "info,health"
    endpoint:
      health:
        show-details: always
    health:
      circuitbreakers:
        enabled: true

spring:
    datasource:
      url: jdbc:h2:mem:countrydb
      #url: jdbc:postgresql://localhost:5432/countrydb
      username: postgres
      password: postgres

      hikari:
        maximum-pool-size: 10

    flyway:
      locations: classpath:db/migration
#      schemas: countries
    jpa:
      hibernate:
        ddl-auto: none

security:
  authentication:
    enabled: true

# these sections are relevant for everything encryption

jasypt:
  encryptor:
    bean: passwordEncryptor
    passphrase: Y2RLQm85NXhjVFZWSDNkaA==

adapter:
  timeout: 10
  calleeservice:
    user: exampleuser
    # by using the ENC() spring-boot-jasypt internally decodes the password
    password: ENC(2UeQbdtDOZZRxoaMXFjM3PC+UsvtauSVVyYfvhrqjw/NnH+zYpdtvWt771L+cUfv)

resilience4j.circuitbreaker:
  configs:
    default:
      #see for more informations under: https://resilience4j.readme.io/docs/circuitbreaker
      registerHealthIndicator: true
      minimumNumberOfCalls: 5
      permittedNumberOfCallsInHalfOpenState: 3
      waitDurationInOpenState: 2s
      failureRateThreshold: 50
      slowCallDurationThreshold: ${adapter.timeout}s
      slowCallRateThreshold: 100.0
      writableStackTraceEnabled: false
  instances:
    calleservice:
      baseConfig: default

