server:
  port: 50700
  tomcat.max-threads: 20

management:
    endpoint:
      health:
        show-details: always
    endpoints:
      web:
        exposure:
          include: "info,health"

info:
    status: ok

spring:
    datasource:
      url: jdbc:h2:mem:countrydb
      #url: jdbc:postgresql://localhost:5432/countrydb
      username: postgres
      password: postgres

      hikari:
        maximum-pool-size: 10

    flyway:
      locations: classpath:db/migration
#      schemas: countries
    jpa:
      hibernate:
        ddl-auto: none

security:
  authentication:
    enabled: true

# these sections are relevant for everything encryption

jasypt:
  encryptor:
    bean: passwordEncryptor
    passphrase: Y2RLQm85NXhjVFZWSDNkaA==

adapter:
  calleeserviceadapter:
    user: exampleuser
    password: ENC(2UeQbdtDOZZRxoaMXFjM3PC+UsvtauSVVyYfvhrqjw/NnH+zYpdtvWt771L+cUfv)
    timeout: 10

    # by using the ENC() spring-boot-jasypt internally decodes the password