server:
  port: 50700
  tomcat.max-threads: 20

management:
    endpoints:
      web:
        exposure:
          include: "info,health"
    endpoint:
      health:
        show-details: always
    health:
      circuitbreakers:
        enabled: true

spring:
    datasource:
      url: jdbc:h2:mem:countrydb
      #url: jdbc:postgresql://localhost:5432/countrydb
      username: example-service
      password: example-service

      hikari:
        maximum-pool-size: 10
        connection-timeout: 10000

    flyway:
      locations: classpath:db/migration

security:
  authentication:
    enabled: true

jasypt:
  encryptor:
    bean: passwordEncryptor
    passphrase: Y2RLQm85NXhjVFZWSDNkaA==

## adapter section

adapter:
  timeout: 10
  calleeservice:
    url: http://localhost:50900
    user: exampleuser
    # by using the ENC() spring-boot-jasypt internally decodes the password
    password: ENC(2UeQbdtDOZZRxoaMXFjM3PC+UsvtauSVVyYfvhrqjw/NnH+zYpdtvWt771L+cUfv)

resilience4j.circuitbreaker:
  configs:
    default:
      #see for more informations under: https://resilience4j.readme.io/docs/circuitbreaker
      registerHealthIndicator: true
      slowCallDurationThreshold: ${adapter.timeout}s #Configures the duration threshold above which calls are considered as slow and increase the rate of slow calls.
      slowCallRateThreshold: 100 #Configures a threshold in percentage. The CircuitBreaker considers a call as slow when the call duration is greater than slowCallDurationThreshold
      failureRateThreshold: 50 #Configures the failure rate threshold in percentage. When the failure rate is equal or greater than the threshold the CircuitBreaker transitions to open and starts short-circuiting calls.
      waitDurationInOpenState: 60s #he time that the CircuitBreaker should wait before transitioning from open to half-open.

      minimumNumberOfCalls: 10 #Configures the minimum number of calls which are required (per sliding window period) before the CircuitBreaker can calculate the error rate.
      permittedNumberOfCallsInHalfOpenState: 10 #Configures the number of permitted calls when the CircuitBreaker is half open.
  instances:
    calleservice:
      baseConfig: default

