apiVersion: v1
kind: ConfigMap
metadata:
  name: ${_Values_app_name}-application-config
data:
  TZ: Europe/Berlin
  server.port: "${_Values_service_port}"

  #monitoring
  server.forward-headers-strategy: FRAMEWORK
  management.database.monitoring.enabled: "true"
  management.endpoints.web.exposure.include: "info,health,heapdump,circuitbreakers,prometheus"

  server.tomcat.threads.max: "20"
  security.authentication.enabled: "false"

---

apiVersion: v1
kind: Secret
metadata:
  name: ${_Values_app_name}-application-config-external
data:


