apiVersion: v1
kind: ConfigMap
metadata:
  name: ${_Values_app_name}-configmap
data:
  TZ: Europe/Berlin
  spring.config.location: /usr/share/config/application.yml
  logging.config: /usr/share/config/logback-rollingfile-spring.xml

  server.port: "${_Values_container_port}"

  #monitoring
  server.forward-headers-strategy: FRAMEWORK
  management.database.monitoring.enabled: "true"
  management.endpoints.web.exposure.include: "info,health,heapdump,circuitbreakers,prometheus"

  #stageing
  server.tomcat.threads.max: "20"


