apiVersion: apps/v1
kind: Deployment
metadata:
  name: callee-service-application
spec:
  selector:
    matchLabels:
      app: callee-service-application
  replicas: 1
  strategy:
    type: Recreate #RollingUpdate
  template:
    metadata:
      annotations:
        linkerd.io/inject: enabled
      labels:
        app: callee-service-application
    spec:
      containers:
        - name: callee-service-application
          image: "${_Values_image_repository}${_Values_server_arch}:${_Values_image_tag}"
          imagePullPolicy: ${_Values_image_pullPolicy}
          ports:
            - name: http
              containerPort: 50100
              protocol: TCP
          env:
            - name: server.port
              value: "50100"
          envFrom:
            - configMapRef:
                name: callee-service-application-configmap
            - secretRef:
                name: callee-service-application-secret

          command: ["java", "-Xms${_Values_resources_requests_memory}", "-Xmx${_Values_resources_requests_memory}",
                    "-Djava.security.egd=file:/dev/./urandom", "-cp", "/app/resources:/app/classes:/app/libs/*",
                    "org.goafabric.calleservice.Application"]
          resources:
            requests:
              memory: "${_Values_resources_requests_memory}"
              cpu: "${_Values_resources_requests_cpu}"

          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: 50100
            initialDelaySeconds: ${_Values_readinessProbe_initialDelaySeconds}
            periodSeconds: 10
            timeoutSeconds: 10
            failureThreshold: 3
          livenessProbe:
            httpGet:
              path: /actuator/health/liveness
              port: 50100
            initialDelaySeconds: ${_Values_readinessProbe_initialDelaySeconds}
            periodSeconds: 10
            timeoutSeconds: 10
            failureThreshold: 3

          volumeMounts:
            - mountPath: /usr/share/logs
              name: callee-service-applogs
            - mountPath: /usr/share/config/
              name: callee-service-application-config-files-volume

      volumes:
        - name: callee-service-applogs
          emptyDir: {}
        # generated from local file system via "kubectl create configmap" inside stack
        - name: callee-service-application-config-files-volume
          configMap:
            name: callee-service-application-config-files
