kind: Service
apiVersion: v1
metadata:
  name: callee-service-application
spec:
  selector:
    app: callee-service-application
  type: ClusterIP #NodePort
  ports:
    - port: 50100
#      nodePort: 30800
      targetPort: http
      protocol: TCP
      name: http

