kind: Service
apiVersion: v1
metadata:
  name: ${_Values_app_name}
spec:
  selector:
    app: ${_Values_app_name}
  type: ${_Values_service_type}
  ports:
    - port: ${_Values_service_port}
      nodePort: ${_Values_service_nodePort}
      targetPort: transport
      protocol: TCP
      name: transport
    - port: ${_Values_jprofiler_port}
      nodePort: 0
      targetPort: jprofiler
      protocol: TCP
      name: jprofiler

