kind: Service
apiVersion: v1
metadata:
  name: callee-service-application
spec:
  selector:
    app: callee-service-application
  ports:
    - protocol: TCP
      port: 50100
#      nodePort: 30800 #this is the external port
#  type: NodePort
  type: ClusterIP