kind: Service
apiVersion: v1
metadata:
  name: ${_Values_app_name}
spec:
  selector:
    app: ${_Values_app_name}
  type: ClusterIP #NodePort
  ports:
    - port: ${_Values_service_port}
#      nodePort: 30800
      targetPort: http
      protocol: TCP
      name: http

