#!/bin/bash

echo Add User admin ...
sudo adduser --ingroup admin admin
sudo usermod -aG sudo admin

sudo sed -i '/PasswordAuthentication no/c PasswordAuthentication yes' /etc/ssh/sshd_config
sudo service ssh restart

echo Please logoff and login with admin again