#!/bin/bash

echo Installing Maven and Java

sudo apt --assume-yes install maven
echo export JAVA_HOME=/usr/lib/jvm/default-java > .bash_profile

echo Building ExampleService
(cd /home/admin ; mkdir projects ; cd projects ; git clone https://github.com/goafabric/spring-boot-example-service ; cd spring-boot-example-service ; mvn package)
