#!/bin/bash

echo Installing Graal
(cd /home/admin ; cd projects ; git clone https://github.com/goafabric/spring-boot-example-graal ; cd spring-boot-example-graal ; git checkout console-only ; ./linux-native-build.sh )

