#!/bin/bash

export COMMAND=$1

function createSecret() {
    kubectl delete secret --ignore-not-found server-certificate-secret -n $1
    kubectl create secret tls server-certificate-secret --cert=./config/goafabric-server.pem --key=./config/goafabric-server.key -n $1
}

if [ "${COMMAND}" = "prov" ]
then
    #we need to do this for all namespaces
    createSecret example
elif [ "${COMMAND}" = "prune" ]
then
    kubectl delete --ignore-not-found secret server-certificate-secret -n example
else
    echo Doing nothing !
fi
