#!/bin/bash

export COMMAND=$1

function delete() {
    kubectl delete secret --ignore-not-found server-certificate-secret -n $1
}

function create() {
    delete $1
    kubectl create secret tls server-certificate-secret --cert=./config/goafabric-server.pem --key=./config/goafabric-server.key -n $1
}

if [ "${COMMAND}" = "init" ]
then
    create kube-system
    create linkerd
    create monitoring
    create example
    elif [ "${COMMAND}" = "prune" ]
then
    delete kube-system
    delete linkerd
    delete monitoring
    delete example
else
    echo Doing nothing !
fi

