kind: Service
apiVersion: v1
metadata:
  name: nginx-service
spec:
  selector:
    app: nginx-service
  ports:
    - protocol: TCP
      port: 50900
      nodePort: 30900 #this is the external port
  type: NodePort