apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-service
spec:
  selector:
    matchLabels:
      app: nginx-service
  replicas: 1
  strategy:
    type: Recreate #RollingUpdate
  template:
    metadata:
      labels:
        app: nginx-service
    spec:
      # initcontainers justs accepts a docker image, and uses postgres client to check readyness
      containers:
        - name: nginx-service
          image: nginx:1.17.10
          imagePullPolicy: Always #IfNotPresent
          ports:
            - containerPort: 50900
          env:
            - name: server.port
              value: "50900"
          envFrom:
            - configMapRef:
                name: nginx-application-configmap
            - secretRef:
                name: nginx-application-secret
          volumeMounts:
            - mountPath: /usr/share/logs
              name: nginx-applogs
            - mountPath: /usr/share/config/
              name: nginx-application-config-files-volume

      volumes:
        - name: nginx-applogs
          emptyDir: {}
        # generated from local file system via "kubectl create configmap" inside stack
        - name: nginx-application-config-files-volume
          configMap:
            name: nginx-application-config-files
