# TODO make container readonly
# TODO Use better names for the services
# TODO HTTPS for nginx

version: '3.7'
services:
  nginx:
    image: nginx:1.15.12-alpine
    container_name: nginx
    #    read_only: true
    restart: always
    environment:
      - TZ=Europe/Berlin
    volumes:
      - ./conf/nginx.conf:/etc/nginx/nginx.conf
      - nginxlogs:/var/log/nginx/logs/
    ports:
      - 8090:80
    networks:
      - example-service-net

volumes:
  nginxlogs:
    driver: local

networks:
  example-service-net:
    external: true