# TODO make container readonly
# TODO Use better names for the services
# TODO HTTPS for nginx

version: '3.7'
services:
  nginx:
    image: nginx:1.17.10
    container_name: nginx
    restart: always
    environment:
      - TZ=Europe/Berlin
    volumes:
      - ./conf/nginx.conf:/etc/nginx/nginx.conf
      - ./ssl/server/goafabric-server.pem:/etc/nginx/ssl/nginx-server.crt
      - ./ssl/server/goafabric-server.key:/etc/nginx/ssl/nginx-server.key
      - nginxlogs:/var/log/nginx/logs/
    ports:
      - 8080:8080
      - 443:443
    networks:
      - example-service-net

volumes:
  nginxlogs:
    driver: local

networks:
  example-service-net:
    external: true