#!/bin/bash

export DAYS_VALID="720"
export ROOT_FILE="root/goafabric-root"
export END_FILE="end-entity/goafabric-endentity"

# create key, won't ask for password because no encryption applied
openssl genrsa\
        -out end-entity/goafabric-endentity.key\
        4096

# create signing request (csr)
openssl req -new -sha512\
        -key ${END_FILE}.key\
        -out ${END_FILE}.csr\
        -config end-entity/san.cnf\
        -extensions SAN

# create end entity certificate
openssl x509 -req -sha512 -days ${DAYS_VALID}\
        -in ${END_FILE}.csr\
        -CA ${ROOT_FILE}.pem\
        -CAkey ${ROOT_FILE}.key\
        -CAcreateserial -out ${END_FILE}.pem\
        -extfile end-entity/san.cnf\
        -extensions SAN


# remove csr
rm end-entity/goafabric-endentity.csr

# direct generation without root ca
#openssl req -x509 -nodes -days 720 -newkey rsa:2048 -keyout goafabric-endentity.key -out goafabric-endentity.pem -subj '/CN=goafabric/O=Goafabric Ltd./C=DE'