#!/bin/bash

export COMMAND=$1

if ! kubectl get --ignore-not-found namespace linkerd | grep -q Active; then exit; fi

if [ "${COMMAND}" = "up" ]
then
    kubectl apply -f ./templates/
elif [ "${COMMAND}" = "down" ]
then
    kubectl delete --ignore-not-found -f ./templates 
else
    echo Doing nothing !
fi
