#!/bin/bash
source .env

export COMMAND=$1

function func_create_application {
    kubectl create configmap callee-service-application-config-files --from-file=./application/config

    kubectl apply -f ./application/
}

function func_delete_application {
    kubectl delete configmap callee-service-application-config-files

    kubectl delete --ignore-not-found -f ./application
}


if [ "${COMMAND}" = "up" ]
then
    func_create_application
    minikube service callee-service-application --url -n ${NAMESPACE}
elif [ "${COMMAND}" = "down" ]
then
    func_delete_application
elif [ "${COMMAND}" = "prune" ]
then
    func_prune
else
    echo Doing nothing !
fi
