#!/bin/bash
source .values

export COMMAND=$1

function up() {
    kubectl create configmap country-service-postgres-initdb --from-file=./config/initdb/ -n ${NAMESPACE}
    kubectl apply -f ./templates/pvc -n ${NAMESPACE}
    kubectl apply -f ./templates/ -n ${NAMESPACE}
    kubectl set image deployment country-service-postgres country-service-postgres=${IMAGE_NAME} -n ${NAMESPACE}
}

function down() {
    kubectl delete --ignore-not-found configmap country-service-postgres-initdb -n ${NAMESPACE}
    kubectl delete --ignore-not-found -f ./templates/ -n ${NAMESPACE}
}

if [ "${COMMAND}" = "up" ]
then
    up
elif [ "${COMMAND}" = "prov" ]
then
    up
elif [ "${COMMAND}" = "down" ]
then
    down
elif [ "${COMMAND}" = "prune" ]
then
    down
    kubectl delete --ignore-not-found -f ./templates/pvc -n ${NAMESPACE}
else
    echo Doing nothing !
fi
