#!/bin/bash

#Minikube Download
echo Download Minikube and Kubectl

#Mac
curl -Lo minikube https://storage.googleapis.com/minikube/releases/latest/minikube-darwin-amd64
curl -LO https://storage.googleapis.com/kubernetes-release/release/$(curl -s https://storage.googleapis.com/kubernetes-release/release/stable.txt)/bin/darwin/amd64/kubectl

#Linux
#curl -Lo minikube https://storage.googleapis.com/minikube/releases/latest/minikube-linux-amd64
#curl -LO https://storage.googleapis.com/kubernetes-release/release/$(curl -s https://storage.googleapis.com/kubernetes-release/release/stable.txt)/bin/linux/amd64/kubectl

chmod +x minikube && sudo mv minikube /usr/local/bin
chmod +x ./kubectl && sudo mv ./kubectl /usr/local/bin/kubectl

#Minikube Delete
minikube delete

#Minikube Config

echo Configure Minikube

minikube config set cpus 4
minikube config set memory 8192
minikube config set vm-driver virtual-box #virtualbox for mac
#minikube config set vm-driver docker #docker or virtualbox for linux

#Minikube Start

minikube start
minikube addons enable metrics-server
minikube addons enable ingress

minikube dashboard