#!/bin/bash
source .values

export COMMAND=$1

function kapply() {
for filename in ./templates/*; do
eval "cat <<EOF
$(<$filename)
EOF
" | kubectl apply -n ${NAMESPACE} -f -
done
}

function up() {
    kubectl create configmap callee-service-application-config-files --from-file=./config -n ${NAMESPACE}
#    kubectl apply -f ./templates/ -n ${NAMESPACE}
    kapply
#    minikube service callee-service-application --url -n ${NAMESPACE}
}

function down() {
    kubectl delete --ignore-not-found configmap callee-service-application-config-files -n ${NAMESPACE}
    kubectl delete --ignore-not-found -f ./templates -n ${NAMESPACE}
}

if [ "${COMMAND}" = "up" ]
then
    up
elif [ "${COMMAND}" = "down" ]
then
    down
elif [ "${COMMAND}" = "prune" ]
then
    down
else
    echo Doing nothing !
fi
