#!/bin/bash
source .values

export COMMAND=$1

if [ "${COMMAND}" = "up" ]
then
    kubectl delete secret --ignore-not-found tls-secret -n ${NAMESPACE}
    kubectl create secret tls tls-secret --cert=./config/goafabric-server.pem --key=./config/goafabric-server.key -n ${NAMESPACE}
elif [ "${COMMAND}" = "down" ]
then
    kubectl delete secret tls-secret -n ${NAMESPACE}
else
    echo Doing nothing !
fi
