#!/bin/bash

echo Installing Virtualbox

wget -q https://www.virtualbox.org/download/oracle_vbox_2016.asc -O- | sudo apt-key add -
wget -q https://www.virtualbox.org/download/oracle_vbox.asc -O- | sudo apt-key add -

sudo nano /etc/apt/sources.list
#deb [arch=amd64] https://download.virtualbox.org/virtualbox/debian bionic contrib

sudo apt-get update
sudo apt-get install virtualbox-6.1

