#!/bin/bash

export COMMAND=$1

if [ "${COMMAND}" = "init" ]
then
    kubectl create namespace monitoring

    kubectl create namespace example
elif [ "${COMMAND}" = "prune-force" ]
then
    kubectl delete namespace monitoring

    kubectl delete namespace example
else
    echo Doing nothing !
fi