#!/bin/bash
source .env

openssl rsa -in goafabric-root.key -out goafabric-root-unencrypted.key

kubectl delete secret tls-secret
kubectl create secret tls tls-secret --cert=goafabric-root.crt --key=goafabric-root-unencrypted.key