#!/bin/bash
source .env

#openssl rsa -in goafabric-root.key -out goafabric-root-unencrypted.key

kubectl delete secret tls-secret
kubectl create secret tls tls-secret --cert=goafabric-server.pem --key=goafabric-server.key