apiVersion: v1
kind: ConfigMap
metadata:
  name: country-service-application-configmap
data:
  TZ: Europe/Berlin
  tomcat.max-threads: "20"
  spring.config.location: /usr/share/config/application.yml
  logging.config: /usr/share/config/logback-rollingfile-spring.xml
  spring.datasource.url: "jdbc:postgresql://country-service-postgres:5432/countrydb"
  management.database.monitoring.enabled: "true"
  adapter.calleeservice.url: "http://callee-service:50900"

---

apiVersion: v1
kind: Secret
metadata:
  name: country-service-application-secret
data:
  spring.datasource.username: ZXhhbXBsZS1zZXJ2aWNl
  spring.datasource.password: Y3JOYjJaNm12QnlTUkt3dQ==


