apiVersion: apps/v1
kind: Deployment
metadata:
  name: country-country-service
spec:
  selector:
    matchLabels:
      app: country-country-service
  replicas: 1
  strategy:
    type: Recreate #RollingUpdate
  template:
    metadata:
      labels:
        app: country-country-service
    spec:
      # initcontainers justs accepts a docker image, and uses postgres client to check readyness
      initContainers:
        - name: check-db-ready
          image: postgres:12.4
          command: ['sh', '-c',
                    'until pg_isready -h country-postgres -p 5432;
                     do echo waiting for database; sleep 2; done;']
      containers:
        - name: country-country-service
          image: goafabric/spring-boot-exampleservice:1.0.4-SNAPSHOT
          imagePullPolicy: Always #IfNotPresent
          ports:
            - containerPort: 50700
          command: ["java", "-Xms256m", "-Xmx256m",
                    "-Djava.security.egd=file:/dev/./urandom", "-cp", "/app/resources:/app/classes:/app/libs/*","org.goafabric.spring.boot.exampleservice.Application"]
          env:
            - name: server.port
              value: "50700"
          envFrom:
            - configMapRef:
                name: country-application-configmap
            - secretRef:
                name: country-application-secret
          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: 50700
            initialDelaySeconds: 20
            periodSeconds: 10
            timeoutSeconds: 10
            failureThreshold: 5
          livenessProbe:
            httpGet:
              path: /actuator/health/liveness
              port: 50700
            initialDelaySeconds: 20
            periodSeconds: 10
            timeoutSeconds: 10
            failureThreshold: 5
          volumeMounts:
            - mountPath: /usr/share/logs
              name: country-applogs
            - mountPath: /usr/share/config/
              name: country-application-config-files-volume
            - mountPath: /src/deploy/demodata/
              name: country-application-demodata-files-volume

      volumes:
        - name: country-applogs
          emptyDir: {}
        # generated from local file system via "kubectl create configmap" inside stack
        - name: country-application-config-files-volume
          configMap:
            name: country-application-config-files
        - name: country-application-demodata-files-volume
          configMap:
            name: country-application-demodata-files
