apiVersion: v1
kind: ConfigMap
metadata:
  name: ${_Values_app_name}-configmap
data:
  TZ: Europe/Berlin
  spring.config.location: /usr/share/config/application.yml
  logging.config: /usr/share/config/logback-rollingfile-spring.xml

  #stageing
  spring.datasource.hikari.maximum-pool-size: "10"
  spring.datasource.hikari.connection-timeout: "10000"

  database.provisioning.goals: -migrate -import-demo-data -terminate # migrate is also needed because we misuse the service as batch here


