apiVersion: v1
kind: Secret
metadata:
  name: ${_Values_app_name}-secret
stringData:
  spring.datasource.url: "jdbc:postgresql://country-service-postgres:5432/country"
data:
  spring.datasource.username: ZXhhbXBsZS1zZXJ2aWNl
  spring.datasource.password: Y3JOYjJaNm12QnlTUkt3dQ==
