apiVersion: v1
kind: Secret
metadata:
  name: ${_Values_app_name}-secret
stringData:
  spring.datasource.url: "jdbc:postgresql://${_Values_root_name}-service-postgres:5432/${_Values_root_name}"
data:
  spring.datasource.username: ZXhhbXBsZS1zZXJ2aWNl
  spring.datasource.password: Y3JOYjJaNm12QnlTUkt3dQ==
