#!/bin/bash
source .values

export COMMAND=$1

function up() {
    kubectl create configmap callee-service-application-config-files --from-file=./config -n ${NAMESPACE}
    kubectl apply -f ./templates/ -n ${NAMESPACE}
    kubectl set image deployment callee-service-application callee-service-application=${IMAGE_NAME} -n ${NAMESPACE}
#    minikube service callee-service-application --url -n ${NAMESPACE}
}

function down() {
    kubectl delete --ignore-not-found configmap callee-service-application-config-files -n ${NAMESPACE}
    kubectl delete --ignore-not-found -f ./templates -n ${NAMESPACE}
}

if [ "${COMMAND}" = "up" ]
then
    up
elif [ "${COMMAND}" = "down" ]
then
    down
elif [ "${COMMAND}" = "prune" ]
then
    down
else
    echo Doing nothing !
fi
