apiVersion: v1
kind: Secret
metadata:
  name: postgres-config
type: Opaque
data:
  POSTGRES_USER: cG9zdGdyZXM=
  POSTGRES_PASSWORD: cG9zdGdyZXM=
  #echo -n 'postgres' | base64
stringData:
  POSTGRES_DB: countrydb

---

apiVersion: v1
kind: ConfigMap
metadata:
  name: example-service-config
data:
  spring.config.location: /usr/share/config/application.yml
  logging.config: /usr/share/config/logback-rollingfile-spring.xml
  spring.datasource.url: "jdbc:postgresql://postgres:5432/countrydb"
  spring.datasource.username: postgres
  spring.datasource.password: postgres
