apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-config
data:
  POSTGRES_USER: postgres
  POSTGRES_PASSWORD: postgres
  POSTGRES_DB: countrydb

---

apiVersion: v1
kind: ConfigMap
metadata:
  name: example-service-config
data:
  spring.config.location: /usr/share/config/application.yml
  logging.config: /usr/share/config/logback-rollingfile-spring.xml
  spring.datasource.url: "jdbc:postgresql://postgres:5432/countrydb"
