kind: Service
apiVersion: v1
metadata:
  name: postgres
spec:
  selector:
    app: postgres
  ports:
    - protocol: TCP
      port: 5432
  type: ClusterIP

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
spec:
  selector:
    matchLabels:
      app: postgres
  replicas: 1
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
        - name: postgres
          image: postgres:9.6.15-alpine
          imagePullPolicy: Always
          ports:
            - containerPort: 5432
          args:
            - postgres
            - -c
            - shared_buffers=128MB
            - -c
            - max_connections=30
            - -c
            - shared_preload_libraries=pg_stat_statements
#          env:
#            - name: POSTGRES_DB
#              value: "countrydb"
          envFrom:
            - configMapRef:
                name: postgres-config
          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: pgdata
      volumes:
        - name: pgdata
