#!/bin/bash

export COMMAND=$1

if [ "${COMMAND}" = "up" ]
then
    ( cd tls ; ./create-secret )
    ( cd callee-service ; ./stack up )
    ( cd country-service ; ./stack up )
elif [ "${COMMAND}" = "down" ]
then
    ( cd callee-service ; ./stack down )
    ( cd country-service ; ./stack down )
elif [ "${COMMAND}" = "prune" ]
then
    ( cd callee-service ; ./stack prune )
    ( cd country-service ; ./stack prune )
else
    echo Doing nothing !
fi
