#!/bin/bash
source .environment
export COMMAND=$1
export SERVICE_MEM="256m"

function func_delete {
    echo delete $1 ...
    kubectl delete services $1
    kubectl delete deployment $1
}

function func_delete_all {
    kubectl config set-context --current --namespace=${NAMESPACE}

    func_delete example-service
    func_delete postgres

    kubectl delete configmap application-config-files
    kubectl delete configmap application-demodata-files
    kubectl delete configmap postgres-initdb

    kubectl delete secret postgres-secret
    kubectl delete secret example-service-secret
    kubectl delete configmap example-service-config
}


if [ "${COMMAND}" = "up" ]
then
    kubectl create namespace ${NAMESPACE}
    kubectl config set-context --current --namespace=${NAMESPACE}

    kubectl create configmap application-config-files --from-file=../config/
    kubectl create configmap application-demodata-files --from-file=../demodata/
    kubectl create configmap postgres-initdb --from-file=../initdb/

    kubectl apply -f configmap.yml
    kubectl apply -f postgres-pvc.yml
    kubectl apply -f postgres.yml
    kubectl apply -f exampleservice.yml

    minikube service example-service --url -n ${NAMESPACE}
elif [ "${COMMAND}" = "down" ]
then
    func_delete_all
elif [ "${COMMAND}" = "prune" ]
then
    func_delete_all
    kubectl delete persistentvolumeclaim postgres-example-pv-claim
    kubectl delete namespace ${NAMESPACE}
    kubectl config set-context --current --namespace=default
else
    echo Doing nothing !
fi
