#!/bin/bash
source .env

export COMMAND=$1
export SERVICE_MEM="256m"

function func_delete {
    echo delete $1 ...
    kubectl delete services $1
    kubectl delete deployment $1
}

function func_delete_all {
    func_delete example-country-service
    func_delete postgres

    kubectl delete configmap example-application-config-files
    kubectl delete configmap example-application-demodata-files
    kubectl delete configmap example-postgres-initdb

    kubectl delete secret example-postgres-secret
    kubectl delete secret example-service-secret
    kubectl delete configmap example-application-configmap
}


if [ "${COMMAND}" = "up" ]
then
    kubectl create configmap example-application-config-files --from-file=../config/application/
    kubectl create configmap example-application-demodata-files --from-file=../demodata/
    kubectl create configmap example-postgres-initdb --from-file=../config/initdb/

    kubectl apply -f ./config/
    kubectl apply -f ./deployment/

    minikube service example-service --url -n ${NAMESPACE}
elif [ "${COMMAND}" = "down" ]
then
    func_delete_all
elif [ "${COMMAND}" = "prune" ]
then
    func_delete_all
    kubectl delete persistentvolumeclaim example-postgres-pvc
else
    echo Doing nothing !
fi
