#!/bin/bash
COMMAND=$1
source .values
kubectl version | grep "Server Version" | grep "linux/arm64" > /dev/null && _Values_server_arch="-arm64v8"

function kapply() {
for filename in ./templates/*.yml; do
eval "cat <<EOF
$(<$filename)
EOF
" | kubectl apply -n ${_Release_namespace} -f -
done
}

function up() {
    [ -d "./config/" ] && kubectl create configmap ${_Values_app_name}-config-files --from-file=./config/ -n ${_Release_namespace}
    [ -d "./config/data/" ] && kubectl create configmap ${_Values_app_name}-data-files --from-file=./config/data/ -n ${_Release_namespace}
    [ -d "./templates/pvc/" ] && kubectl apply -f ./templates/pvc/ -n ${_Release_namespace}
    [ -d "./templates/ingress/" ] && kubectl apply -f ./templates/ingress/ -n ${_Release_namespace}
    kapply
}

function down() {
    [ -d "./config/" ] && kubectl delete --ignore-not-found configmap ${_Values_app_name}-config-files -n ${_Release_namespace}
    [ -d "./config/data/" ] && kubectl delete --ignore-not-found configmap ${_Values_app_name}-data-files -n ${_Release_namespace}
    [ -d "./templates/ingress/" ] && kubectl delete --ignore-not-found -f ./templates/ingress/ -n ${_Release_namespace}
    kubectl delete --ignore-not-found -f ./templates -n ${_Release_namespace}
}

function prune() {
    down
    [ -d "./templates/pvc/" ] && kubectl delete --ignore-not-found -f ./templates/pvc/ -n ${_Release_namespace}
}

if [ "${COMMAND}" = "import" ]
then
    prune
    up
    echo waiting for batch to start/load
    while ! kubectl get pods -n ${_Release_namespace} | grep ${_Values_app_name} | grep Running > /dev/null; do sleep 1; done
    kubectl logs --follow -l app=${_Values_app_name} -n ${_Release_namespace}
elif [ "${COMMAND}" = "prune" ]
then
    prune
else
    echo Doing nothing !
fi
