#!/bin/bash

export COMMAND=$1

if [ "${COMMAND}" = "init" ]
then
    kubectl apply -f ./templates/
elif [ "${COMMAND}" = "prune" ]
then
    kubectl delete -f ./templates/
else
    echo Doing nothing !
fi