apiVersion: v1
kind: Secret
metadata:
  name: ${_Values_app_name}-secret
type: Opaque
stringData:
  POSTGRES_DB: country
data:
  POSTGRES_USER: ZXhhbXBsZS1zZXJ2aWNl
  #echo -n example-service | base64
  #echo -n ZXhhbXBsZS1zZXJ2aWNl | base64 -d
  POSTGRES_PASSWORD: Y3JOYjJaNm12QnlTUkt3dQ==
  #echo -n crNb2Z6mvBySRKwu | base64
  #echo -n Y3JOYjJaNm12QnlTUkt3dQ== | base64 -d