apiVersion: v1
kind: ConfigMap
metadata:
  name: ${_Values_app_name}-configmap
data:
  TZ: Europe/Berlin
  POSTGRES_DB: countrydb

---

kind: ConfigMap
apiVersion: v1
metadata:
  name: ${_Values_app_name}-initdb-files
data:
  00_pg_statements.sql: |-
    CREATE EXTENSION pg_stat_statements;



