apiVersion: apps/v1
kind: Deployment
metadata:
  name: ${_Values_app_name}
spec:
  selector:
    matchLabels:
      app: ${_Values_app_name}
  replicas: 1
  strategy:
    type: Recreate #RollingUpdate
  template:
    metadata:
      annotations:
        linkerd.io/inject: ${_Values_linkerd_inject}
      labels:
        app: ${_Values_app_name}
    spec:
      containers:
        - name: ${_Values_app_name}
          image: "postgres:13.1"
          imagePullPolicy: IfNotPresent #Always
          ports:
            - containerPort: ${_Values_ports_containerPort}
          envFrom:
            - configMapRef:
                name: ${_Values_app_name}-configmap
            - secretRef:
                name: ${_Values_app_name}-secret

          args:
            - postgres
            - -c
            - shared_buffers=128MB
            - -c
            - max_connections=30
            - -c
            - shared_preload_libraries=pg_stat_statements
          resources:
            requests:
              memory: "128M"
              cpu: "250m"
            limits:
              cpu: "500m"

          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: ${_Values_app_name}-pvc-volume

      volumes:
        - name: ${_Values_app_name}-pvc-volume
          persistentVolumeClaim:
            claimName: ${_Values_app_name}-pvc