kind: Service
apiVersion: v1
metadata:
  name: country-service-postgres
spec:
  selector:
    app: country-service-postgres
  ports:
    - protocol: TCP
      port: 5432
      nodePort: 30710 #this is the external port
  #type: ClusterIP
  type: NodePort
