kind: Service
apiVersion: v1
metadata:
  name: country-service-postgres
spec:
  selector:
    app: country-service-postgres
  type: NodePort #ClusterIP
  ports:
    - port: ${_Values_service_port}
      nodePort: 30710
      targetPort: transport
      protocol: TCP
      name: tcp
