#!/bin/bash
source .env

export COMMAND=$1

function func_create_application {
    kubectl create configmap country-service-application-config-files --from-file=../../config/application/

    kubectl apply -f ./deployment/application/
}

function func_create_postgres {
    kubectl create configmap country-service-application-demodata-files --from-file=../../config/postgres/demodata/
    kubectl create configmap country-service-postgres-initdb --from-file=../../config/postgres/initdb/

    kubectl apply -f ./deployment/postgres/
}

function func_delete_application {
    kubectl delete configmap country-service-application-config-files

    kubectl delete --ignore-not-found -f ./deployment/application/
}

function func_delete_postgres {
    kubectl delete configmap country-service-postgres-initdb
    kubectl delete configmap country-service-application-demodata-files

    kubectl delete --ignore-not-found -f ./deployment/postgres/
}

if [ "${COMMAND}" = "up" ]
then
    func_create_postgres
    func_create_application
#    minikube service country-service-application --url -n ${NAMESPACE}
elif [ "${COMMAND}" = "down" ]
then
    func_delete_application
    func_delete_postgres
elif [ "${COMMAND}" = "prune" ]
then
    func_delete_application
    func_delete_postgres
    kubectl delete persistentvolumeclaim country-service-postgres-pvc
else
    echo Doing nothing !
fi
