#!/bin/bash
source .values
export COMMAND=$1

function up() {
    kubectl create configmap country-service-application-demodata-files --from-file=./config/demodata/ -n ${NAMESPACE}
    kubectl create configmap country-service-application-config-files --from-file=./config -n ${NAMESPACE}
    kubectl apply -f ./templates/ -n ${NAMESPACE}
    kubectl set image deployment country-service-application country-service-application=${IMAGE_NAME} -n ${NAMESPACE}
    minikube service country-service-application --url -n ${NAMESPACE}
}

function down() {
    kubectl delete --ignore-not-found configmap country-service-application-demodata-files -n ${NAMESPACE}
    kubectl delete --ignore-not-found configmap country-service-application-config-files -n ${NAMESPACE}
    kubectl delete --ignore-not-found -f ./templates -n ${NAMESPACE}
}


if [ "${COMMAND}" = "up" ]
then
    up
elif [ "${COMMAND}" = "prov" ]
then
    up
    echo provisioning ...
    kubectl wait --timeout=60s --for=condition=ready pod --selector app=country-service-application -n ${NAMESPACE}
    echo done provisioning
elif [ "${COMMAND}" = "down" ]
then
    down
elif [ "${COMMAND}" = "prune" ]
then
    down
else
    echo Doing nothing !
fi

